services:
  - name: editor-video-api
    env: python
    build:
      apt:
        packages:
          - imagemagick
          - ffmpeg
          - libmagickwand-dev  # Paquete adicional necesario
    envVars:
      - key: IMAGEMAGICK_BINARY
        value: /usr/bin/convert  # Ruta explícita al binario
      - key: FFMPEG_BINARY
        value: /usr/bin/ffmpeg