services:
  - name: editor-video-api
    env: python
    pythonVersion: "3.12"  # Usa Python 3.12 que es más estable
    build:
      apt:
        packages:
          - imagemagick
          - ffmpeg
          - libmagickwand-dev
    envVars:
      - key: IMAGEMAGICK_BINARY
        value: /usr/bin/convert
      - key: FFMPEG_BINARY
        value: /usr/bin/ffmpeg